# (Do not change) Indicates the configuration file format.
version: 4

# Choose the language for plugin messages (supported: en/English, pt/Portuguese).
# To use custom messages, refer to the plugin documentation:
# todo: link to documentation
language: en

# Enables automatic checks for plugin updates on startup.
checkForUpdates: true

## Worlds Configuration (Optional)
# Defines the default scoreboards displayed in each world.
# You can use regular expressions to match multiple worlds.
# Supportes regex.
worlds:
  world_the_end: [ 'conditional', 'simple' ]
  world_\w*: [ 'customTiming' ]
  '[\w\- ]*': [ 'simple' ]

## Player Data Storage (Optional)
# Allows you to save player data to a database.
# Changing storage settings requires a server restart.
storage:
  # Supported database drivers:
  #  Local: H2, SQLite
  #  Remote: PostgreSQL, MariaDB, MySQL
  # Set to "none" to disable player data saving.
  driver: H2
  # Sets a prefix for SimpleScore tables.
  tablePrefix: simplescore_

  # Database Details (Remote Only).
  address: 127.0.0.1:3306
  database: minecraft
  username: simplescore
  password: '|D/-\55\^/0|2|)'

  # HikariCP's connection pool settings for remote databases.
  # The default provided settings should work fine for most server setups.
  # You shouldn't modify them unless you understand connection pooling.
  pool:
    # Maximum number of connections in the pool.
    maximumPoolSize: 8
    # Minimum idle connections maintained.
    minimumIdle: 8
    # Maximum connection lifetime in milliseconds.
    maxLifetime: 1800000
    # Interval for testing connection aliveness (in milliseconds).
    keepaliveTime: 0
    # Connection timeout in milliseconds.
    connectionTimeout: 5000
    # Additional properties for the database driver.
    extraProperties:
      useUnicode: true
      characterEncoding: utf8

## Advanced Settings
# Do not modify unless you know the implications.

# Controls the frequency of the update task in ticks.
# Changes require a server restart.
taskUpdateTime: 1
