name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon --build-cache

      - name: Generate Changelog
        id: generate_changelog
        run: |
          git fetch --unshallow --tags
          tag=$(git tag --sort version:refname | tail -n 2 | head -n 1)
          if [ "$tag" ]; then
            changelog=$(git log --oneline --no-decorate $tag..HEAD)
          else
            changelog=$(git log --oneline --no-decorate)
          fi
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A' - }"
          changelog=" - ${changelog//$'\r'/'%0D'}"
          echo "CHANGELOG<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$changelog" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.generate_changelog.outputs.CHANGELOG }}
          files: build/libs/*.jar
          draft: true
